[package]
name = "sanskrit-typeck"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
sanskrit-diagnostics = { path = "../sanskrit-diagnostics" }
sanskrit-ast = { path = "../sanskrit-ast" }
sanskrit-hir = { path = "../sanskrit-hir" }
serde = { version = "1.0", features = ["derive"] }
