title: Sanskrit Programming Language
description: A modern programming language inspired by Sanskrit
theme: jekyll-theme-cayman

# Navigation
nav:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: Documentation
    url: /docs
  - title: Examples
    url: /examples
  - title: Contributing
    url: /contributing

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
