[package]
name = "sanskrit-parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
sanskrit-diagnostics = { path = "../sanskrit-diagnostics" }
sanskrit-lexer = { path = "../sanskrit-lexer" }
sanskrit-ast = { path = "../sanskrit-ast" }
serde = { version = "1.0", features = ["derive"] }
